name: tgcm-decompose-review
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7.16
  - pip=22.3.1
  - pytorch=1.13.1
  - cpuonly
  - numpy=1.18.5
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - pip:
      - tensorflow==1.15.5
      - tensorflow-estimator==1.15.1
      - protobuf==3.20.3
      - h5py==2.10.0
      - decompose @ git+https://github.com/bethgelab/decompose.git@b6ad3e3d1a2d049f1853cdc309ad042293415ad1
